### DISCUSSION TITLE
How to set dynamic values inside <style> tag?

### DISCUSSION THREAD

**Discussion by derpycoder** [a-h/templ#1020] [General]
```css
<style type="text/css">
  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-Regular.woff2")}) format("woff2");
     font-weight: normal;
     font-style: normal;
     font-display: swap;
  }

  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-SemiBold.woff2") }) format("woff2");
     font-weight: 600;
     font-style: normal;
     font-display: swap;
  }

  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-Medium.woff2") }) format("woff2");
     font-weight: 500;
     font-style: normal;
     font-display: swap;
  }
</style>
```
