### DISCUSSION TITLE
Hot-reload with templ proxy and air

### DISCUSSION THREAD

**Discussion by leandergangso** [a-h/templ#596] [Show and tell]
I wanted to use `air` (for obvious reasons) as well as the `templ proxy` to have hot-reloading in my browser, and this is the solution I've come up with.

It works by running `air` and `templ` separately, and using the templ -cmd flag to run a script that will trigger a new rebuild in air.

Do note that sometimes `air` is not fast enough to rebuild GO before `templ` has sent the reload event and the browser reloaded, in those cases you'll have to do a manual reload.
Also it seems like there are some optimization that can be done in templ to better determine when rebuilding GO is needed.

Anyhow, here are the files, just copy them into your project and run `make dev` to start your app. :smile: 

`airtempl` (make it executable: `chmod +x airtempl`)
```bash
#!/usr/bin/env bash

file="airtempl.txt"

# Check if file exists, if not create it
touch $file 

# Increment the value in file
echo $(( $(<$file) + 1 )) > $file 
```

`makefile`
```makefile
dev: # -j flag specify how many 'jobs' to run at once for the make cmd
    $(MAKE) -j 2 air watch

air: # need this for make cmd
   air

watch:
    templ generate -watch -proxy="http://localhost:8080" -cmd="./airtempl"
```

`air.toml`
```toml
root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ." # change this as needed
  delay = 1 # as fast as possible (is faster than having 0)
  exclude_dir = ["tmp", "vendor", "view"] # can exclude the dir for your templ files instead of regex bellow
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"] # don't want to detect templ.go files
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "txt"] # don't work with just include_file, so need to include "txt" here (probably a bug in air?)
  include_file = ["airtempl.txt"] # need to include this as to detect when to update based on templ
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
 
[log]
  main_only = true # true: for cleaner output
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
```
