### ISSUE TITLE
How to set dynamic values inside <style> tag?

### ISSUE THREAD

**Issue by derpycoder** [a-h/templ#1021]
```css
<style type="text/css">
  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-Regular.woff2")}) format("woff2");
     font-weight: normal;
     font-style: normal;
     font-display: swap;
  }

  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-SemiBold.woff2") }) format("woff2");
     font-weight: 600;
     font-style: normal;
     font-display: swap;
  }

  @font-face {
    font-family: "Poppins";
src: url({ AssetPath("asset_src/fonts/Poppins-Medium.woff2") }) format("woff2");
     font-weight: 500;
     font-style: normal;
     font-display: swap;
  }
</style>

```

I want to add critical css and dynamic paths in templ, is it not possible to have css dynamic?

Also, the syntax highlighting is off inside style tags.

Will it be supported?

What’s the alternative, how do I approach this problem?
