### ISSUE TITLE
New CSS arg feature - rotation transform getting sanitized

### ISSUE THREAD

**Issue by dseravalli** [a-h/templ#506]
I'm trying to use the newly added css args feature on `main` to generate a rotation transform and it looks like it's getting sanitized.

```go
css windVaneRotation(degrees float64) {
  transform: { fmt.Sprintf("rotate(%ddeg)", int(math.Round(degrees))) };
}
```

resulting class:
```css
.windVaneRotation_244c{transform:zTemplUnsafeCSSPropertyValue;}
```
