### ISSUE TITLE
Render css classes inside <style></style>

### ISSUE THREAD

**Issue by marianvlad** [a-h/templ#953]
Hi,

I have a component Layout with a parameter called styles of type string. There is a way to use like this?

```go
styles := "body { color: red; }"
```

```css
<style>{ styles }</style> 

and return

<style>body { color: red; }</style>

instead

<style>{ styles }</style> 
```

✅ Found the solution

```go
styles := "<style>body { color: red; }</style>"
```

```html
@templ.Raw(styles)
```
